modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="maid_travel_camera"
version="0.0.3"
displayName="MaidTravelCamera"
authors="Fast_xiang"
description="fast mod"

[[dependencies.fast]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fast]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"